[prompt]
double = false
color = [115, 147, 179]
text_color = [33, 33, 33]
promptchar = "Î»"
style = "arrow"

[misc]
alias = [
]

[effects]
underlined = true
bold = true
dimmed = true
suggestion_color = "cyan"

truecolors = true 
true_suggestion_color = [128,128,128]
