require('v9.plugins')
require('v9.options')
require('v9.configuration.indent-blankline')
require('v9.configuration.bufferline')
require('v9.configuration.nvim-tree')
require('v9.configuration.presence')
require('v9.configuration.statusline')
require('v9.keybinds')
